version: 2

jobs:
  build_&_test:
    docker:
      - image: circleci/golang:1.12
    steps:
      - checkout
      - restore_cache:
          keys:
            - go-{{ checksum "go.sum" }}
            - go-

      - run: go mod vendor
      - save_cache:
          key: go-{{ checksum "go.sum" }}
          paths:
            - "vendor"

      - run: go test -v ./...
      - run: go build

      - store_artifacts:
          path: ops-cli
          destination: ops-cli

workflows:
  version: 2
  all:
    jobs:
      - build_&_test
