version: 2

jobs:
  build_&_test:
    docker:
      - image: circleci/golang:1.12
    steps:
      - checkout
      - restore_cache:
          keys:
            - go-{{ checksum "go.sum" }}
            - go-

      - run: go mod vendor
      - save_cache:
          key: go-{{ checksum "go.sum" }}
          paths:
            - "vendor"
      - run:
          name: Test
          command: |
            mkdir -p test-reports
            GO111MODULE=off go get github.com/jstemmer/go-junit-report
            go test -v ./... -count=1 -coverprofile=c.out | go-junit-report > test-reports/junit.xml
      - run: go build

      - store_artifacts:
          path: ops-cli
          destination: ops-cli

      - attach_workspace:
          at: ./artifacts

      - run: cp ops-cli ./artifacts/

      - persist_to_workspace:
          root: ./artifacts
          paths:
            - ops-cli

      - run:
          name: Setup Code Climate test-reporter
          command: |
            curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
            chmod +x ./cc-test-reporter

      - run:
          name: Upload coverage results to Code Climate
          command: |
            ./cc-test-reporter format-coverage -t gocov -p github.com/Pocket/ops-cli
            ./cc-test-reporter upload-coverage

      - store_test_results:
          path: test-reports

      - store_artifacts:
          path: coverage
          destination: coverage

  publish-github-release:
    docker:
      - image: cibuilds/github:0.12
    steps:
      - attach_workspace:
          at: ./artifacts
      - run:
          name: "Publish Release on GitHub"
          command: |
            VERSION=$(./artifacts/ops-cli --version)
            ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete ${VERSION} ./artifacts/


workflows:
  version: 2
  all:
    jobs:
      - build_&_test:
          tags:
            only: /^\d+\.\d+\.\d+$/
      - publish-github-release:
          requires:
            - build_&_test
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^\d+\.\d+\.\d+$/