version: 2

jobs:
  build_&_test:
    docker:
      - image: circleci/golang:1.12
    steps:
      - checkout
      - restore_cache:
          keys:
            - go-{{ checksum "go.sum" }}
            - go-

      - run: go mod vendor
      - save_cache:
          key: go-{{ checksum "go.sum" }}
          paths:
            - "vendor"
      - run:
          name: Test
          command: |
            mkdir -p test-reports
            GO111MODULE=off go get github.com/jstemmer/go-junit-report
            go test -v ./... -count=1 -coverprofile=c.out | go-junit-report > test-reports/junit.xml
      - run: go build

      - store_artifacts:
          path: ops-cli
          destination: ops-cli

      - run:
          name: Setup Code Climate test-reporter
          command: |
            curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
            chmod +x ./cc-test-reporter

      - run:
          name: Upload coverage results to Code Climate
          command: |
            ./cc-test-reporter format-coverage -t gocov -p github.com/Pocket/ops-cli
            ./cc-test-reporter upload-coverage

      - store_test_results:
          path: report.xml

      - store_artifacts:
          path: coverage
          destination: coverage


workflows:
  version: 2
  all:
    jobs:
      - build_&_test
